version: '3.8'
services:
  func-api:
    image: func-api:1.0.1
    ports:
      - '8088:8081'
    environment:
      KAFKA_CLIENT_ID: FuncManagerClientId
      KAFKA_GROUP_ID: FuncManagerGroupId
      BOOTSTRAPSERVER: 127.0.0.1:19092
      DB_USER: sa
      DB_PASSWORD: LocalAdmin_123
      DB_SERVER: localhost
      DB_DATABASE: tempdb
      FUNC_TOPICS: Demo-WORKFLOW
  func-manager:
    image: func-manager:1.0.1
    ports:
      - '8080:80'
    environment:
      FUNC_API_URL: func-api:8088/
    depends_on:
      - func-api
