version: '3.8'
services:
  func-manager:
    image: func-manager:local-dev
    ports:
      - '8080:80'
    environment:
      FUNC_API_URL: http://localhost:8082/
    depends_on:
      - "func-api"
    networks:
      - managernetwork
  func-api:
    image: func-api:local-dev
    ports:
      - '8082:3000'
    environment:
      KAFKA_CLIENT_ID: FuncManagerClientId
      KAFKA_GROUP_ID: FuncManagerGroupId
      BOOTSTRAPSERVER: func_kafka1:9092
      DB_USER: sa
      DB_PASSWORD: LocalAdmin_123
      DB_SERVER: database
      DB_DATABASE: tempdb
      FUNC_TOPICS: RetryProcess-WORKFLOW
    depends_on:
      - "database"
      - "func_kafka1"
    networks:
      - managernetwork
  func_zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    user: root
    hostname: func_zookeeper
    container_name: func_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: none
    networks:
      - managernetwork
  func_kafka1:
    image: confluentinc/cp-server:6.0.1
    user: root
    hostname: func_kafka1
    container_name: func_kafka1
    depends_on:
      - func_zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'func_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://func_kafka1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_ADVERTISED_HOST_NAME: func_kafka1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    logging:
      driver: none
    networks:
      - managernetwork
  func_kafka2:
    image: confluentinc/cp-server:6.0.1
    user: root
    hostname: func_kafka2
    container_name: func_kafka2
    depends_on:
      - func_zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'func_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://func_kafka2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_HOST_NAME: func_kafka2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    logging:
      driver: none
    networks:
      - managernetwork
  func_kafka3:
    image: confluentinc/cp-server:6.0.1
    user: root
    hostname: func_kafka3
    container_name: func_kafka3
    depends_on:
      - func_zookeeper
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'func_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://func_kafka3:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_ADVERTISED_HOST_NAME: func_kafka3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    logging:
      driver: none
    networks:
      - managernetwork
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - "1433:1433"
    container_name: database
    hostname: database
    environment:
      TZ: Europe/Berlin
      SA_PASSWORD: "LocalAdmin_123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      timeout: 3s
      interval: 5s
      retries: 5
    volumes:
      - ./create-database.sql:/app/create-database.sql
      - ./run-initialization.sh:/app/run-initialization.sh
      - ./entrypoint.sh:/app/entrypoint.sh
    command: /app/entrypoint.sh
    networks:
      - managernetwork
networks:
  managernetwork:
    external: false